### Login
POST http://127.0.0.1:5000/login
Content-Type: application/json

{
  "username" : "Admin3",
  "password" : "admineasy12#"
}


### live
POST https://us-central1-mobiledev-428400.cloudfunctions.net/nutripal_live1/login
Content-Type: application/json

{
  "username" : "Admin3",
  "password" : "admineasy12#"
}

### Signup
POST http://127.0.0.1:5000/signup
Content-Type: application/json

{
  "username" : "Admin3",
  "email" : "admin3@gmail.com",
  "password" : "admineasy12#",
  "height" : "179",
  "weight" : "87",
  "dob" : "02/02/02",
  "phone_number" : "0251231256"
}

### Send OTP to client
POST https://us-central1-mobiledev-428400.cloudfunctions.net/nutripal_live1/send_otp
Content-Type: application/json

{
  "phone_number" : "2330556207957"
}

### Verify client OTP
POST https://us-central1-mobiledev-428400.cloudfunctions.net/nutripal_live1/verify_otp
Content-Type: application/json

{
  "code" : 105508,
  "phone_number" : "2330556207957"
}

### Set user goals
PATCH http://127.0.0.1:5000/set_goals
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcxOTg2ODM2NCwianRpIjoiZDgzOTc5NjktYTUwNC00YzQ0LThlZDktNTYwOTJlMTk1ZTk1IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkFkbWluMyIsIm5iZiI6MTcxOTg2ODM2NCwiY3NyZiI6IjMyOWI4OTc2LWQ2NGEtNDQ1Ny1iYzI2LTg3ZjllNTNlMGNhYyIsImV4cCI6MTcxOTg2OTI2NH0.PfrXHWxDn7hEuLe4IIX1-Uo-ttbxv1Yf8lcEozKhKjA

{
  "steps" : 10000,
  "calories" : 1800
}

### Update a user profile
PATCH http://127.0.0.1:5000/update_account
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMDgyNDU0OSwianRpIjoiM2U1YTY5MTQtZGM3Ni00ODllLWFkMTctODg1NGEwOTBkYTcyIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkFkbWluMyIsIm5iZiI6MTcyMDgyNDU0OSwiY3NyZiI6ImE3NjA5MzcxLWE1OGYtNDI1Ny04NzQ5LTMzMGFlNDU3M2VhOSIsImV4cCI6MTcyMDgyNTQ0OX0.3uHEYu_T-EV_vGX6RudV_ISUbzcs7-pwOdkX-aJ4Jmo

{
  "height" : "200",
  "weight" : "89",
  "phone_number" : "233556207957"
}


### Get a user profile
GET http://127.0.0.1:5000/view_account
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMDgyNDU0OSwianRpIjoiM2U1YTY5MTQtZGM3Ni00ODllLWFkMTctODg1NGEwOTBkYTcyIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkFkbWluMyIsIm5iZiI6MTcyMDgyNDU0OSwiY3NyZiI6ImE3NjA5MzcxLWE1OGYtNDI1Ny04NzQ5LTMzMGFlNDU3M2VhOSIsImV4cCI6MTcyMDgyNTQ0OX0.3uHEYu_T-EV_vGX6RudV_ISUbzcs7-pwOdkX-aJ4Jmo



### Share recipe
GET http://127.0.0.1:5000/share_recipe/9somdz7UJIARzwAddZms
Content-Type: application/json
